# if clavis url is not set fake key generation will be used instead
# clavis_url = "tcp://192.168.10.101:5560"

max_key_cnt = 1000000

# both aija and brencis qkdc services
# can be hosted from the same process
# if aija or brencis is commented out
# its qkdc service will not be hosted
aija_port = 8080
brencis_port = 8081