# maximum number of keys to be buffered
max_key_cnt = 100000

# both aija and brencis qkdc services
# can be hosted from the same process
# if aija or brencis is commented out
# its qkdc service will not be hosted
aija_port = 8080
brencis_port = 8081

# possible gatherers values: "pseudorandom", "clavis", "filesystem"
gatherer = "pseudorandom"

# if gatherer is set to "clavis" clavis url is required
# clavis_url = "tcp://192.168.10.101:5560"

# if gatherer is set to "filesystem" directory path is required
fs_gatherer_dir = "/tmp/qkd-mock"


# logging every request may be useful for debugging
log_info = true
log_debug = false

# default serving can be true or false.
# if false, set state request with RUNNING must be made to receive keys.
default_serving = false